// Generated by CoffeeScript 1.7.1
var fs;

fs = require('fs');

exports.index = function(req, res) {
  return res.render('index');
};

exports.upload = function(req, res) {
  return res.render("upload");
};

exports.file_upload = function(req, res) {
  var files;
  files = req.files;
  fs.rename(files.file.path, 'uploads\\' + files.file.name, function() {});
  res.writeHead(200, {
    'Content-Type': 'text/plain'
  });
  res.write(files.file.name);
  res.end();
};

exports.login = function(req, res) {
  var password, username;
  username = res.username;
  password = res.password;
};
